// Canonical card data shared by the About and Projects pages.
export const projectCards = [
  {
    name: 'Pet Detective',
    url: '/pet-detective/',
    description: 'Solver and solution library for Lumosity\'s Pet Detective puzzle.',
    image: '/screenshots/pet-detective.png',
    featured: true,
    crop: [0.33, 0.82],
    tags: ['Rust', 'Optimisation', 'Puzzle'],
  },
  {
    name: 'VectorMation',
    url: '/VectorMation/',
    description: 'Vector-based math animation engine, an SVG-driven alternative to manim.',
    image: '/screenshots/vectormation.svg',
    tags: ['Python', 'SVG', 'Rendering'],
  },
  {
    name: 'Master Thesis',
    url: '/MasterThesis/',
    description: 'Decoding CSIDH: a guide to isogeny-based cryptography. Leiden University.',
    image: '/screenshots/master-thesis.png',
    tags: ['Cryptography', 'LaTeX', 'Number Theory'],
  },
  {
    name: 'Padel Scheduler',
    url: '/padel/',
    description: 'Create mathematically optimal padel tournaments.',
    image: '/screenshots/padel.png',
    crop: [0, 0.5],
    tags: ['Linear Programming', 'Optimisation', 'PDF-generation'],
  },
  {
    name: 'Durak AI Helper',
    url: '/durak-online/',
    description: 'Play Durak against AI opponents or get MCTS suggestions for a real-life game.',
    image: '/screenshots/durak-online.png',
    featured: true,
    crop: [0, 0.5],
    tags: ['Rust', 'WebAssembly', 'MCTS'],
  },
  {
    name: 'Bachelor Thesis',
    url: '/BachelorThesis/',
    description: 'Methods for reducing error in approximations of the Rayleigh integral. TU Delft.',
    image: '/screenshots/bachelor-thesis.png',
    tags: ['Numerical Methods', 'LaTeX'],
  },
  {
    name: 'Tango',
    url: '/tango/',
    description: 'Practice your skills in the LinkedIn tango game!',
    image: '/screenshots/tango.png',
    featured: true,
    tags: ['LinkedIn', 'Svelte', 'Puzzle'],
  },
  {
    name: 'Practice Math',
    url: '/practice-math/',
    description: 'Tool for practicing math, currently focused on derivatives.',
    image: '/screenshots/practice-math.png',
    crop: [0, 0.38],
    tags: ['Derivatives', 'Math'],
  },
  {
    name: 'Equal Sums of Powers',
    url: 'https://powersums.jorisperrenet.com/',
    description: 'A searchable leaderboard and verified archive of equal sums of like powers, near misses, and computational records.',
    image: '/screenshots/equal-sums-of-powers.png',
    featured: true,
    tags: ['Leaderboard', 'Number Theory', 'Open Data'],
  },
  {
    name: 'Primes in Arithmetic Pro­gres­sion',
    url: 'https://github.com/jorisperrenet/arithmetic-progression',
    description: 'GPU-accelerated search for arithmetic progressions of primes, used to break multiple records.',
    tags: ['CUDA', 'C++', 'Rust', 'Number Theory'],
  },
  {
    name: 'Iscripts',
    url: 'https://github.com/jorisperrenet/iscripts/blob/master/INSTALL.md',
    description: 'Installation scripts and a detailed setup guide for my Arch Linux configuration.',
    tags: ['Bash', 'Arch Linux'],
  },
  {
    name: 'Diag­nos­tic Questions (NL)',
    url: '/diagnostische-vragen/',
    description: 'Curated academic references on diagnostic questions in education (Dutch).',
    lang: 'nl',
    tags: ['Svelte', 'Education'],
  },
];
